[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "benthoscan"
version = "0.0.1"
description = "A small API for 3D reconstruction and registration based on images"
authors = ["Martin Kvisvik Larsen <martin.kvisvik.larsen@hotmail.com>"]
readme = "README.md"
packages = [{include = "benthoscan", from="src"}]
package-mode = true

[tool.poetry.dependencies]
python = "^3.11"
arrow = "^1.3.0"
h5py = "^3.11.0"
loguru = "^0.7.2"
numpy = "^1.26.4"
pandas = "^2.2.2"
python-dotenv = "^1.0.1"
result = "^0.16.1"
toml = "^0.10.2"
tqdm = "^4.66.2"
open3d = "0.18.0"
pyyaml = "^6.0.1"
polars = "^0.20.30"
jupyter = "^1.0.0"
plotly = "^5.22.0"
metashape = {path = "vendor/Metashape-2.1.0-cp37.cp38.cp39.cp310.cp311-abi3-linux_x86_64.whl"}
scipy = "^1.13.1"
scikit-learn = "^1.5.0"
addict = "^2.4.0"
pillow = "^10.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
black = "^24.4.2"
jupyter = "^1.0.0"
ruff = "^0.4.9"

[tool.poetry.scripts]
create = "benthoscan.cli.entrypoint:main"
reconstruct = "benthoscan.cli.entrypoint:main"
register = "benthoscan.cli.entrypoint:main"
