[camera]
camera_type = "stereo"
group_name = "auv_stereo"

# TODO: Add camera group with type, sensor labels

[camera.labels]
master = "stereo_left_label"
slave = "stereo_right_label"

[camera.sensor]
master = "stereo_master"
slave = "stereo_slave"
slave_offset = [0.07, 0.0, 0.0]
slave_rotation = [0.0, 0.0, 0.0]

[reference.column_maps]
identifier = { label = "stereo_left_label" }
geolocation = { longitude = "longitude", latitude = "latitude", height = "height" }
orientation = { roll = "roll", pitch = "pitch", heading = "heading" }

[reference.constants]
geolocation_accuracy = [3.0, 3.0, 0.2]   # accuracy in meters
orientation_accuracy = [10.0, 5.0, 5.0]  # accuracy in degrees
