[[chunk]]
name = "r7jjskxq_20101023_210332"
image_directory = "acfr_images_processed/r7jjskxq_20101023_210332_images"
camera_data = "acfr_cameras_prior/r7jjskxq_20101023_210332_cameras.csv"
camera_config = "config/sensors/stereo_config.toml"

[[chunk]]
name = "r7jjskxq_20121013_060425"
image_directory = "acfr_images_processed/r7jjskxq_20121013_060425_images"
camera_data = "acfr_cameras_prior/r7jjskxq_20121013_060425_cameras.csv"
camera_config = "config/sensors/stereo_config.toml"

[[chunk]]
name = "r7jjskxq_20131022_004934"
image_directory = "acfr_images_processed/r7jjskxq_20131022_004934_images"
camera_data = "acfr_cameras_prior/r7jjskxq_20131022_004934_cameras.csv"
camera_config = "config/sensors/stereo_config.toml"

