[[chunk]]
name = "CHUNK_NAME"
image_directory = "acfr_images_processed/CHUNK_NAME_images"
camera_data = "acfr_cameras_prior/CHUNK_NAME_cameras.csv"
camera_config = "config/sensors/stereo_config.toml"

