[[chunk]]
name = "qdch0ftq_20100428_020202"
image_directory = "acfr_images_processed/qdch0ftq_20100428_020202_images"
camera_file = "acfr_cameras_prior/qdch0ftq_20100428_020202_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "qdch0ftq_20110415_020103"
image_directory = "acfr_images_processed/qdch0ftq_20110415_020103_images"
camera_file = "acfr_cameras_prior/qdch0ftq_20110415_020103_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "qdch0ftq_20120430_002423"
image_directory = "acfr_images_processed/qdch0ftq_20120430_002423_images"
camera_file = "acfr_cameras_prior/qdch0ftq_20120430_002423_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "qdch0ftq_20130406_023610"
image_directory = "acfr_images_processed/qdch0ftq_20130406_023610_images"
camera_file = "acfr_cameras_prior/qdch0ftq_20130406_023610_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "qdch0ftq_20140327_071251"
image_directory = "acfr_images_processed/qdch0ftq_20140327_071251_images"
camera_file = "acfr_cameras_prior/qdch0ftq_20140327_071251_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "qdch0ftq_20170526_025746"
image_directory = "acfr_images_processed/qdch0ftq_20170526_025746_images"
camera_file = "acfr_cameras_prior/qdch0ftq_20170526_025746_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "qdch0ftq_20210315_034028"
image_directory = "acfr_images_processed/qdch0ftq_20210315_034028_images"
camera_file = "acfr_cameras_prior/qdch0ftq_20210315_034028_cameras.csv"
camera_config = "config/stereo_config.toml"
