[[chunk]]
name = "r234xgje_20100604_230524"
image_directory = "acfr_images_processed/r234xgje_20100604_230524_images"
camera_file = "acfr_cameras_prior/r234xgje_20100604_230524_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "r234xgje_20120530_064545"
image_directory = "acfr_images_processed/r234xgje_20120530_064545_images"
camera_file = "acfr_cameras_prior/r234xgje_20120530_064545_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "r234xgje_20140616_205232"
image_directory = "acfr_images_processed/r234xgje_20140616_205232_images"
camera_file = "acfr_cameras_prior/r234xgje_20140616_205232_cameras.csv"
camera_config = "config/stereo_config.toml"
