[[chunk]]
name = "r23685bc_20100605_021022"

[chunk.directories]
images = "/home/martin/data/acfr_debug/r23685bc/20100605_021022/images"
data = "/home/martin/data/acfr_debug/r23685bc/20100605_021022"

[chunk.files]
cameras = "20100605_021022_cameras.csv"
references = "20100605_021022_cameras.csv"

[chunk.settings]
cameras = ".config/stereo-camera.toml"
references = ".config/reference.toml"



[[chunk]]
name = "r23685bc_20120530_233021"

[chunk.directories]
images = "/home/martin/data/acfr_debug/r23685bc/20120530_233021/images"
data = "/home/martin/data/acfr_debug/r23685bc/20120530_233021"

[chunk.files]
cameras = "20120530_233021_cameras.csv"
references = "20120530_233021_cameras.csv"

[chunk.settings]
cameras = ".config/stereo-camera.toml"
references = ".config/reference.toml"



[[chunk]]
name = "r23685bc_20140616_225022"

[chunk.directories]
images = "/home/martin/data/acfr_debug/r23685bc/20140616_225022/images"
data = "/home/martin/data/acfr_debug/r23685bc/20140616_225022"

[chunk.files]
cameras = "20140616_225022_cameras.csv"
references = "20140616_225022_cameras.csv"

[chunk.settings]
cameras = ".config/stereo-camera.toml"
references = ".config/reference.toml"
