[[chunk]]
name = "r29mrd12_20090613_010853"
image_directory = "acfr_images_processed/r29mrd12_20090613_010853_images"
camera_file = "acfr_cameras_prior/r29mrd12_20090613_010853_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "r29mrd12_20090613_104954"
image_directory = "acfr_images_processed/r29mrd12_20090613_104954_images"
camera_file = "acfr_cameras_prior/r29mrd12_20090613_104954_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "r29mrd12_20110612_045149"
image_directory = "acfr_images_processed/r29mrd12_20110612_045149_images"
camera_file = "acfr_cameras_prior/r29mrd12_20110612_045149_cameras.csv"
camera_config = "config/stereo_config.toml"

[[chunk]]
name = "r29mrd12_20130611_015335"
image_directory = "acfr_images_processed/r29mrd12_20130611_015335_images"
camera_file = "acfr_cameras_prior/r29mrd12_20130611_015335_cameras.csv"
camera_config = "config/stereo_config.toml"
