[[reference]]
source = "table"
group = "stereo_left"

[reference.accuracies]
position = [2.0, 2.0, 0.2]
orientation = [2.0, 2.0, 5.0]

[reference.formats]
position = "WGS84"
orientation = "YPR"

# Maps from table columns to camera fields
[reference.fields]
label = "stereo_left_label"

position = [
    { name="x", column="longitude", required=true, default=0.0 },
    { name="y", column="latitude", required=true, default=0.0 },
    { name="z", column="height", required=true, default=0.0 },
]

orientation = [
    { name="x", column="yaw", required=true, default=0.0 },
    { name="y", column="pitch", required=true, default=0.0 },
    { name="z", column="roll", required=true, default=0.0 },
]
