[global]
type = "ransac"

[global.preprocess]
downsample = { voxel_size = 0.20 }
estimate_normals = { radius = 0.60 }

[global.parameters]
correspondence_distance = 0.30
feature_radius = 2.00
feature_neighbours = 500
estimate_scale = true
sample_count = 3
max_iterations = 200000
confidence = 0.9999



[[incremental]]
type = "icp"

[incremental.preprocess]

[incremental.parameters]




[full]
type = "pose_graph"
