[fpfh]
voxel_size = 0.10
fpfh_radius = 1.50
fpfh_nn = 900
max_iterations = 100000
confidence = 0.999
max_distance = 0.15
edge_length = 0.80
normal_angle = 5.00

[icp]
max_iterations = 200
max_distance = 0.15
