[camera_config]
name = "auv_stereo"
label_keys = ["stereo_left_filename", "stereo_right_filename"]

[reference]
position_format = "WGS84"
position_fields = ["latitude", "longitude", "height"]
orientation_format = "RPY"
orientation_fields = ["roll", "pitch", "yaw"]
