# Image groups

[filegroup]
label = "auv_stereo"
keys = ["stereo_left_filename", "stereo_right_filename"]

# Camera tying the image groups together
[camera.config]
label = "auv_stereo"
components = [ 
    {"stereo_left" : "stereo_left_filename"}, 
    {"stereo_right" : "stereo_right_filename"},
]

[reference.position]
format = "WGS84"
fields = ["latitude", "longitude", "height"]

[reference.orientation]
format = "RPY"
fields = ["roll", "pitch", "yaw"]
